#Find the Average Temperature for Each Day

CREATE TABLE temperature_readings (
    sensor_id number,
    reading_time TIMESTAMP,
    temperature number
);

alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss';
INSERT all  
 INTO temperature_readings  VALUES(1, to_DatE('2024-07-01 08:00:00','yyyy-mm-dd hh24:mi:ss'), 25.4)
 INTO temperature_readings VALUES (1, to_DatE('2024-JUL-01 12:00:00','yyyy-mm-dd hh24:mi:ss'),27.8)
 INTO temperature_readings VALUES (1, to_DatE('2024-JUL-01 16:00:00','yyyy-mm-dd hh24:mi:ss'),29.2)
 INTO temperature_readings VALUES (2, to_DatE('2024-JUL-02 08:00:00','yyyy-mm-dd hh24:mi:ss'),24.7)
 INTO temperature_readings VALUES (2, to_DatE('2024-JUL-02 12:00:00','yyyy-mm-dd hh24:mi:ss'),26.3)
 INTO temperature_readings VALUES (2, to_DatE('2024-JUL-02 16:00:00','yyyy-mm-dd hh24:mi:ss'),28.1)
 INTO temperature_readings VALUES (3, to_DatE('2024-JUL-03 08:00:00','yyyy-mm-dd hh24:mi:ss'), 23.5)
 INTO temperature_readings VALUES (3, to_DatE('2024-JUL-03 12:00:00','yyyy-mm-dd hh24:mi:ss'), 25.0)
 INTO temperature_readings VALUES (3, to_DatE('2024-JUL-03 16:00:00','yyyy-mm-dd hh24:mi:ss'), 27.6)
 INTO temperature_readings VALUES (1, to_DatE('2024-JUL-04 08:00:00','yyyy-mm-dd hh24:mi:ss'), 22.9)
select * from dual;


-- retrieve the total revenue generated by each product 

select to_char(reading_time,'DD-MON-YYYY'), round(AVG(TEMPERATURE),2)
from  temperature_readings
GROUP BY  to_char(reading_time,'DD-MON-YYYY')
order by 1
