CREATE TABLE products (
    product_id number PRIMARY KEY,
    product_name VARCHAR2(100),
    product_price number
);

CREATE TABLE Orders  (
    OrderID NUMBER PRIMARY KEY,
    ProductID NUMBER,
    Quantity NUMBER,
    OrderDate DATE,
    FOREIGN KEY (ProductID) REFERENCES Products(product_id)
);


INSERT all INTO products  VALUES(1, 'product A',10.00)
INTO products  VALUES(2, 'product B',15.00)
INTO products  VALUES(3, 'product C',20.00)
INTO products  VALUES(4, 'product D',25.00)
INTO products  VALUES(5, 'product E',30.00)
INTO products  VALUES(6, 'Product F', 35.00)
INTO products  VALUES(7, 'Product G', 40.00)
INTO products  VALUES(8, 'Product H', 45.00)
INTO products  VALUES(9, 'Product I', 50.00)
INTO products  VALUES(10, 'Product J', 55.00)
select * from dual;


alter session set nls_date_format='yyyy-mm-dd';
INSERT all INTO Orders (OrderID, ProductID, Quantity, OrderDate) VALUES(1, 1, 2, '2023-07-01')
INTO Orders VALUES (2, 2, 1, '2023-07-02')
INTO Orders VALUES(3, 3, 5, '2023-07-03')
INTO Orders VALUES(4, 1, 3, '2023-07-04')
INTO Orders VALUES(5, 5, 2, '2023-07-05')
INTO Orders VALUES(6, 6, 1, '2023-07-06')
INTO Orders VALUES(7, 2, 4, '2023-07-07')
INTO Orders VALUES(8, 8, 3, '2023-07-08')
INTO Orders VALUES(9, 9, 1, '2023-07-09')
INTO Orders VALUES(10, 10, 2, '2023-07-10')
select * from dual;
select * from Orders ;

-- retrieve the total revenue generated by each product 

select p.product_name,sum(product_price*Quantity)
from products p ,Orders o
where p.product_id=o.ProductID
group by  p.product_name
order by substr(PRODUCT_NAME,instr(PRODUCT_NAME,' '),2);

--find products that have not been ordered at all 
select  p.product_id,p.product_name
from products p ,Orders o
where p.product_id=o.ProductID(+)
and o.ProductID is null 
